#!/bin/sh

rm -f *.jpg *.png *.gif

mk()
{
	img=$1
	chan=$2
	loc=${3:-freeview}
	typ=`echo $1 | awk -F. '{print $NF}'`
	[ -n "$chan" ] && ln -s $loc/"$img" "$chan.$typ"
	[ "$typ" != "jpg" ] && ln -s "$chan.$typ" "$chan.jpg"

	echo "$img"
}

mk BBC-one_logo.jpg			"BBC ONE"
mk BBC-two_logo.jpg			"BBC TWO"
mk BBC-three_logo.jpg			"BBC THREE"
mk BBC-FOUR_logo.jpg			"BBC FOUR"
mk BBC-1-HD_logo.jpg			"BBC One HD"
mk BBC-HD_logo.jpg			"BBC HD"
mk BBC-NEWS_logo.jpg			"BBC NEWS"
mk BBC-PARLIAMENT_logo.jpg		"BBC Parliament"
mk BBC-RED-BUTTON_logo.jpg		"301"
mk CBeebies_logo.jpg			"CBeebies"
mk cbbc_logo.jpg			"CBBC Channel"

mk itv-1_logo.jpg			"ITV1"
mk ITV1-1_logo.jpg			"ITV1 +1"
mk itv-2_logo.jpg			"ITV2"
mk itv-2-1_logo.jpg			"ITV2 +1"
mk itv-3_logo.jpg			"ITV3"
mk itv-4_logo.jpg			"ITV4"
mk Citv_logo.jpg			"CITV"
mk ITV1-HD_logo.jpg			"ITV1 HD"

mk channel-4_logo.jpg			"Channel 4"
mk channel-4-1_logo.jpg			"Channel 4+1"
mk MORE-4_logo.jpg			"More 4"
mk E4_logo.jpg				"E4"
mk E4-1_logo.jpg			"E4+1"
mk FILM-4_logo.jpg			"Film4"
mk 4-MUSIC_logo.jpg			"4Music"
mk 4HD_logo.jpg				"Channel 4 HD"
mk S4-C_logo.jpg			"S4C"
mk S4C-Clirlun_logo.jpg			"Clirlun"

mk five_logo.jpg			"Channel 5"
mk Five_logo.jpg			"5*"
mk 5-USA_logo.jpg			"5 USA"

mk Big-Deal_logo.jpg			"Big Deal"
mk Challenge-TV_logo.jpg		"Challenge"
mk Create-and-Craft_logo.jpg		"Create & Craft"
mk Dave_logo.jpg			"Dave"
mk Dave-Ja-Vu_logo.jpg			"Dave ja vu"

mk Pick-TV_logo.jpg			"Pick TV"
mk Pick-TV_logo.jpg			"Pick TV+1"
mk Yesterday_logo.jpg			"Yesterday"
mk QVC_logo.jpg				"QVC"
mk QVC-Beauty_logo.jpg			"QVC Beauty"
mk VIVA_logo.jpg			"VIVA"
mk ideal-WORLD_logo.jpg			"Ideal World"
mk bid-tv_logo.jpg			"bid tv"
mk price-drop-tv_logo.jpg		"price-drop tv"
mk Quest_logo.jpg			"QUEST"
mk Daystar_logo.jpg			"Daystar"
mk SKY-NEWS_logo.jpg			"Sky News"
mk Russia-Today_logo.jpg		"Russia Today"
mk community-channel_logo.jpg		"COMMUNITY"
mk Teletext-holidays_logo.jpg		"Teletext Hols"
mk skytext_logo.jpg			"Sky Text"
mk alsmallchannel_logo.jpg
mk teleg_logo.jpg

mk BBC-Radio-1_logo.jpg			"BBC Radio 1"
mk BBC-Radio-2_logo.jpg			"BBC Radio 2"
mk BBC-RADIO-3_logo.jpg			"BBC Radio 3"
mk BBC-RADIO-4_logo.jpg			"BBC Radio 4"
mk BBC-RADIO-5-live-sports_logo.jpg	"BBC R5SX"
mk BBC-RADIO-5-live_logo.jpg		"BBC R5L"
mk BBC-RADIO-6-music_logo.jpg		"BBC 6 Music"
mk BBC-RADIO-A_logo.jpg			"BBC Asian Net."
mk BBC-Radio-1Xtra_logo.jpg		"BBC R1X"
mk BBC-Radio-4-Extra_logo.jpg		"BBC Radio 4 Ex"
mk BBC-WORLD-SERVICE_logo.jpg		"BBC World Sv."

mk Absolute_logo.jpg			"Absolute Radio"
mk Capital-Radio_logo.jpg		"Capital FM"
mk KERRAND!-Radio_logo.jpg		"Kerrang!"
mk KISS-Radio_logo.jpg			"Kiss"
mk heart-Radio_logo.jpg			"Heart"
mk heat-Radio_logo.jpg			"heat"
mk magic-Radio_logo.jpg			"Magic"
mk smash!-Radio_logo.jpg		"Smash Hits!"
mk smooth-RADIO_logo.jpg		"SMOOTH RADIO"
mk talkSPORT_logo.jpg			"talkSPORT"
mk the-hits_logo.jpg			"The Hits Radio"
mk Premier-CHRISTIAN-RADIO_logo.jpg	"Premier Radio"
mk Q-Radio_logo.jpg			"Q"
mk U105.8_logo.jpg			"U105"

mk logo_tn_tvx.jpg			"Television X"
mk logo_tn_gems.gif			"Gems TV"

mk harmonyOne_88X150_SkySportsOne.jpg	"Sky Sports 1" cam
mk harmonyOne_88X150_SkySportsTwo.jpg	"Sky Sports 2" cam
mk rocks_and_co.jpg			"Rocks & Co 1" cam
mk espn.jpg				"ESPN" cam
mk home_uktv.jpg			"Home" cam

