#!/bin/sh

if [ "`cat /etc/model`" = HD ]; then
	epg=/media/drive1/epgsavedata
	epgdb=/media/drive1/epg.db
else
	epg=/mnt/hd1/dvbepg/epg.dat
	epgdb=/mnt/hd1/epg.db
fi

case "$1" in
	start)
		/mod/bin/epg -f $epg sqlitedumpd $epgdb > /tmp/epgd.log 2>&1 &
		;;
	stop)
		killall -q epg
		;;
	*)
		exit 1
		;;
esac

exit 0

