#!/bin/sh

export tmpf=/tmp/cronf.$$

# Add cron jobs

crond=$PKG_ROOT/var/spool/cron/crontabs
[ -d $crond ] || exit 1

cronf=$crond/root
grep -v webif/lib/bin/auto $cronf > $tmpf
(
	cat $tmpf
	echo '*/10 * * * * /mod/webif/lib/bin/auto >/dev/null 2>&1'
) > $cronf

# Add anacron jobs

ana=$PKG_ROOT/etc/anacrontab
grep -v 'backup/backup.jim' $ana > $tmpf
(
	cat $tmpf
	echo "1 8 sched_backup /mod/var/mongoose/cgi-bin/backup/backup.jim"
) > $ana

$PKG_ROOT/etc/init.d/S02anacron start < /dev/null > /dev/null 2>&1 &

[ -f /tmp/webif_auto.log ] && rm -f /tmp/webif_auto.log

exit 0

