#!/bin/sh

# Relocate any stray files in /mod/var/mongoose

if [ -d /mod/var/mongoose -a ! -h /mod/var/mongoose ]; then
	(
		cd /mod/var/mongoose
		find . | cpio -pmud /mod/webif
		cd /mod/var
		rm -rf mongoose
		ln -s ../webif mongoose
	)
fi

export tmpf=/tmp/cronf.$$

# Add cron jobs

crontab=$PKG_ROOT/bin/crontab
if [ -x $crontab ]; then
	$crontab -l | grep -v webif/lib/bin/auto > $tmpf
	cat $tmpf - << EOM | $crontab -
*/10 * * * * /mod/webif/lib/bin/auto >/dev/null 2>&1
EOM
fi

# Add anacron jobs

ana=$PKG_ROOT/etc/anacrontab
egrep -v 'backup/backup.jim|bin/diskattrs' $ana > $tmpf
cat $tmpf - << EOM > $ana
1 8 sched_backup /mod/webif/html/backup/backup.jim
1 5 diskattrs /mod/webif/lib/bin/diskattrs
EOM

$PKG_ROOT/etc/init.d/S02anacron start < /dev/null > /dev/null 2>&1 &

[ -f /tmp/webif_auto.log ] && rm -f /tmp/webif_auto.log

if [ ! -f /mod/webif/.strip-updated ]; then
	echo "*********************************"
	echo "* Please wait while any shrunk recordings are flagged..."
	echo "*********************************"
	/mod/webif/lib/bin/strip-update

	touch /mod/webif/.strip-updated
fi

/mod/webif/lib/bin/diskattrs
#/mod/webif/lib/bin/resetnew

# Remove hook script placed by the legacy rt3070 package which does not work
# with CFW >= 3.00
hook=/mod/boot/xinit.d/rt3070
[ -f $hook ] && rm -f $hook

# Migrate record log to new name.
(
	cd /mod/tmp
	[ -f record.log -a ! -f activity.log ] && mv record.log activity.log
)

[ -f $tmpf ] && rm -f $tmpf

exit 0

