#!/bin/sh

# Handle moving the legacy /var/mongoose directory to /webif..

if [ -h /mod/webif -a -d /mod/var/mongoose -a ! -h /mod/var/mongoose ]; then
	echo "Relocating web interface files..."

	cd /mod
	rm webif || exit 1
	mv var/mongoose webif || exit 1
	cd var
	ln -s ../webif mongoose
fi

if [ ! -f /mod/webif/.pfixpkg ]; then
	at now + 1 minute << EOM
diag fixpkg
touch /mod/webif/.pfixpkg
EOM
fi

exit 0

