#!/bin/sh

export tmpf=/tmp/cronf.$$

cronf=$PKG_ROOT/var/spool/cron/crontabs/root
if [ -f $cronf ]; then
	grep -v webif/lib/bin/auto $cronf > $tmpf
	cp $tmpf $cronf
	[ -s $cronf ] || rm -f $cronf
fi

ana=/mod/etc/anacrontab
egrep -v 'backup/backup.jim|diskattrs' $ana > $tmpf
cp $tmpf $ana

exit 0

