#!/bin/sh

export tmpf=/tmp/cronf.$$

crontab=$PKG_ROOT/bin/crontab
if [ -x $crontab ]; then
	$crontab -l | grep -v webif/lib/bin/auto > $tmpf
	[ -s $tmpf ] && $crontab $tmpf || $crontab -r
fi

ana=/mod/etc/anacrontab
egrep -v 'backup/backup.jim|bin/diskattrs' $ana > $tmpf
cp $tmpf $ana

[ -f $tmpf ] && rm -f $tmpf

exit 0

